approvedGitRepositories:
  - "**"

enableGlobalCache: false

enableScripts: true

enableTelemetry: false

nodeLinker: pnp

npmMinimalAgeGate: 0

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.17.1.cjs
